# Copyright 2021 Google LLC
# Copyright 2022 Andrew Pritchard
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: portray-prettyprinter
version: 0.2.1
category: Text
synopsis: Portray backend for prettyprinter
description: |
  This provides a
  <https://hackage.haskell.org/package/prettyprinter prettyprinter> backend for
  <https://hackage.haskell.org/package/portray portray> along with derivable
  'Pretty' instances for types with 'Portray' instances.

  This backend has largely superseded the original
  <https://hackage.haskell.org/package/portray-pretty portray-pretty>.  Because
  @prettyprinter@ gives more flexibility to documents at the cost of requiring
  more behavior to be specified explicitly, some formats are nicer with this
  backend, configurable syntax highlighting is supported, and unicode escaping
  is configurable.  However, as this backend is still newer, there are
  potentially more unnoticed formatting bugs.  Please do file bugs on the
  GitHub issue tracker if you find anything that seems obviously wrong!

  Try using 'pp' as the print function in GHCi:
  @:set -interactive-print=Data.Portray.Prettyprinter.pp@!
license: Apache-2.0
author: Andrew Pritchard <awpritchard@gmail.com>
copyright: 2021 Google LLC; 2022 Andrew Pritchard
maintainer: Andrew Pritchard <awpritchard@gmail.com>
github: awpr/portray/portray-prettyprinter

# Note: this causes CHANGELOG.md to be included in Hackage distributions.
extra-source-files:
  CHANGELOG.md

dependencies:
  - base >= 4.12 && < 4.18
  - portray >= 0.3 && < 0.4
  - portray-diff >= 0.1 && < 0.2
  - prettyprinter >= 1.2 && < 1.8
  - prettyprinter-ansi-terminal >= 1.1.1 && < 1.2
  - text >= 0.1 && < 2.1

library:
  source-dirs: src
  exposed-modules:
    - Data.Portray.Prettyprinter

  when:
    condition: false
    other-modules: Paths_portray_prettyprinter

tests:
  PortrayPrettyprinter-test:
    source-dirs: test
    main: Main.hs
    dependencies:
      - portray
      - portray-prettyprinter
      - test-framework
      - test-framework-hunit
      - test-framework-quickcheck2
      - HUnit
      - QuickCheck

    when:
      condition: false
      other-modules: Paths_portray_prettyprinter
