problemMatcher:
  - owner: stack-ghc
    pattern:
      - regexp: '^([^:]+):(\d+):(\d+):\s+(error|warning):.*((?:\n.+)*)'
        file: 1
        line: 2
        column: 3
        severity: 4
        message: 5
