# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: portray-diff-hunit
version: 0.1.0.0
category: Data
synopsis: Equality assertion functions for HUnit based on portray-diff.
description: |
    This provides equality assertion functions for HUnit that pretty-print
    structural diffs of the values in question, rather than dumping the entire
    alues as part of the counterexamples.  This is useful when comparing very
    large values, since it can otherwise be difficult to tell what changed
    between expected and actual values.
license: Apache-2.0
author: Reiner Pope <reinerp@google.com>
copyright: 2018-2021 Google LLC
maintainer: Andrew Pritchard <awpr@google.com>
github: google/hs-portray/portray-diff-hunit

# Note: this causes CHANGELOG.md to be included in Hackage distributions.
extra-source-files:
  CHANGELOG.md

dependencies:
  - HUnit >= 1.1 && < 1.7
  - base >= 4.12 && < 4.16
  - portray-diff >= 0.1 && < 0.2
  - portray-pretty >= 0.1 && < 0.2
  - pretty >= 1.1.3 && < 1.2

library:
  source-dirs: src
  exposed-modules:
    - Data.Portray.Diff.HUnit

  when:
    condition: false
    other-modules: Paths_portray_diff_hunit
